- server/build.gradle
- server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
- server/src/test/java/com/codueon/boostUp/BoostUpApplicationTests.java
* Member Entity 추가
* dependency 충돌로 인한 Spring Boot 버전 변경
> feat: Member Entity 추가 및 Spring Boot 버전 변경

- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- Suggest Entity 작성
- PaymentInfo Entity 작성
> feat: Suggest Entity 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- SuggestStatus enum 추가 및 Getter 작성
> feat: SuggestStatus 추가

- server/src/main/java/com/codueon/boostUp/domain/bookmark/entity/Bookmark.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
- Review Entity 작성
- Bookmark Entity Getter 및 NoArgsConstructor 어노테이션 추가
> feat: Review Entity 작성 및 Bookmark Entity 수정

- server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
- server/src/main/java/com/codueon/boostUp/domain/member/exception/AuthException.java
- server/src/main/java/com/codueon/boostUp/global/exception/BusinessLogicException.java
- server/src/main/java/com/codueon/boostUp/global/exception/ErrorResponse.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
- server/src/main/java/com/codueon/boostUp/global/exception/GlobalAdvice.java
- server/src/main/java/com/codueon/boostUp/global/webhook/SendErrorToDiscord.java
- server/src/main/java/com/codueon/boostUp/global/webhook/ServiceError.java
- server/src/main/java/com/codueon/boostUp/global/webhook/WebHookError.java
- server/src/main/java/com/codueon/boostUp/global/webhook/WebHookFeign.java
* Global Exception 추가
* Exception 디스코드 웹 훅 연동
> feat: global exception 및 디스코드 webhook 추가

- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/CareerImage.java
##변경 사항
- fileSize String -> Long으로 수정
> refactor: Lesson Entity 리펙토링

- server/src/main/java/com/codueon/boostUp/domain/member/entity/Token.java
> feat: 토큰 엔티티 추가

- server/build.gradle
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Address.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
> fix: languages 엔티티 충돌 수정

- server/.gitignore
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostPaymentUrl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/SuggestResponse.java
DTO 작성
- PostSuggest
- PostPaymentUrl
- SuggestResponse
- gitignore 수정
> feat: Suggest DTO 작성

- server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
> feat: Bookmark DTO 작성

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetDetailLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetMypageLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostEditLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
- 상세페이지 조회
- 마이페이지 조회
- 과외 등록
- 과외 수정
> feat: Lesson DTO 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetSuggest.java
- 컨벤션에 맞도록 SuggestResponse -> GetSuggest DTO 이름 변경
> refactor: GetSuggest DTO 이름 변경

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetDetailLesson.java
> refatcor: GetDetailLesson DTO 생성자 리펙토링

- server/src/main/java/com/codueon/boostUp/domain/dto/MultiResponseDto.java
- server/src/main/java/com/codueon/boostUp/domain/dto/PageInfo.java
- server/src/main/java/com/codueon/boostUp/domain/dto/SingleResponseDto.java
- MultiResponseDto 작성
- SingleResponseDto 작성
- PageInfo 작성
> feat: 공통 DTO 작성

- server/src/main/java/com/codueon/boostUp/global/util/Auditable.java
> feat: Auditable 작성

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
> feat: Lesson Controller 구조 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- Suggest Controller 구조 작성
- 환불 기능 추가 시 환불 API 작성
> feat: Suggest Controller 구조 작성

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostSearchLesson.java
> refactor: Lesson DTO에 검색 추가

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostSearchLesson.java
> refactor: Lesson Controller에 검색 추가

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
> refactor: PostLesson 리펙토링

- server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/reviewController.java
> feat: Review Controller 작성

- server/build.gradle
- server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
- server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostMessage.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/req/PostRoom.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChat.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatMember.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetChatRoom.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/res/GetLastChat.java
- server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
- server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
- server/src/main/java/com/codueon/boostUp/domain/chat/entity/RedisChat.java
- server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisPublisher.java
- server/src/main/java/com/codueon/boostUp/domain/chat/redis/RedisSubscriber.java
- server/src/main/java/com/codueon/boostUp/domain/chat/repository/ChatRepository.java
- server/src/main/java/com/codueon/boostUp/domain/chat/repository/RoomRepository.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/RoomService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostEditLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Address.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Language.java
- server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
- server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
* RedisTemplete 채팅 Config 추가
* Chat 관련 Entity 추가
* Chat 관련 Repository 추가
Review 기능 구현을 완료한 후 추후 Security가 적용되는데로 기능을 구현할 예정입니다!
또한 논의 후 알람 기능도 추후 구현해볼 생각입니다.
> feat: chatting 기능 controller - service - repository 구현중

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- SuggestDbService 기본 구조 작성
- - Suggest DTO 수정
- Suggest Controller 작성중
- Suggest Service 작성중
-
> feat: SuggestDbService 기본 구조 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- postSuggest 과외 신청하기 기능 구현
- security 구현 후 memberId 수정
> feat: postSuggest 과외 신청하기 기능 구현

- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- postSuggest 과외 신청하기 테스트 코드 작성
- Spring Rest Docs는 추후 구현 예정
> test: postSuggest 과외 신청하기 테스트 코드 작성

- server/build.gradle
- server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
- server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
> feat: Member 공통 DB 서비스 작성

- server/src/main/java/com/codueon/boostUp/domain/dto/MultiResponseDto.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/reviewController.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PostReview.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/CustomReviewRepository.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
- server/src/main/java/com/codueon/boostUp/global/util/Auditable.java
* 리뷰 생성(결제 완료 예외처리는 주석처리했습니다)
* 과외 상세페이지 리뷰 전체 조회
* ExceptionCode 정리
* MultiResponseDto Page List만 넘기는 식으로 변경
결제 - Security - MemberDbService가 완성되면 추가 보완할 예정입니다~
> feat: 리뷰 작성 및 상세페이지 리뷰 전체조회 구현

- server/build.gradle
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/global/config/AwsS3Config.java
> feat : S3 Server 환경 구성 중

- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- Lesson 엔티티 career String을 Integer로 변경
> refactor: lesson 엔티티 career String을 Integer로 변경

- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
- server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
- server/src/main/java/com/codueon/boostUp/security/config/SecurityConfig.java
- server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberCreateTest.java
> feat: 회원가입 기능 구현/ 보안 적용 중

- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- Suggest Entity StartTime/EndTime 추가
- Status 삭제 및 이름 변경
> feat: Suggest Entity StartTime/EndTime 추가

- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- getTeacherSuggest 테스트
- getStudentSuggest 테스트
추후 기능 구현 코드 변경 시 테스트도 변경될 예정
> test: getSuggest 테스트 코드 작성

- server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonAddress.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPostTest.java
* 리뷰 생성 테스트
* 상세페이지 리뷰 전체 조회 테스트
* 마이페이지 리뷰 전체 조회 테스트
시큐리티, RestDoc을 제외한 테스트 코드는 작성했고 수정 / 삭제는 내일 하겠습니다!
* LessonAddress 엔티티에 Address 필드 오타 수정(adress -> address)
> test: Review 조회 테스트 코드 작성

- server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetAllDetailReviews.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
* 북마크 Contoller API 분리
* Review Dto 수정
북마크 브런치인데 Review 수정도 실수로 같이 올려서 1, 2 나눠서 풀 리퀘스트 하겠습니다! 죄송합니다.
> refactor: 북마크 API 변경 + Review Dto 수정 - 1

- server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
* 북마크 Contoller API 분리
* Review Dto 수정
북마크 브런치인데 Review 수정도 실수로 같이 올려서 1, 2 나눠서 풀 리퀘스트 하겠습니다! 죄송합니다.
> refactor: 북마크 API 변경 + Review Dto 수정 - 2

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetTeacherSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- tabId if문 -> switch문 변경
- switch문 사용을 위해 tabId Long -> int 변경
수정 전
```
private BooleanExpression changeStatusByTabId(Long tabId) {
if(tabId == 1) return suggest.status.eq(Suggest.SuggestStatus.ACCEPT_IN_PROGRESS);
else if(tabId == 2) {
return suggest.status.eq(Suggest.SuggestStatus.PAY_IN_PROGRESS).and(
suggest.status.eq(Suggest.SuggestStatus.DURING_LESSON));
} else return suggest.status.eq(Suggest.SuggestStatus.END_OF_LESSON);
} 
```
수정 후
```
private BooleanExpression changeStatusByTabId(int tabId) {
switch (tabId) {
case 1: return suggest.status.eq(Suggest.SuggestStatus.ACCEPT_IN_PROGRESS);
case 2: return suggest.status.eq(Suggest.SuggestStatus.PAY_IN_PROGRESS).and(
suggest.status.eq(Suggest.SuggestStatus.DURING_LESSON));
default: return …
```
> refactor: getSuggest tabId if문 -> switch문 변경

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- 과외 신청 취소 기능 구현
- SuggestController에 lesson 오타 -> suggest 변경
> feat: deleteSuggest 과외 신청 취소 기능 구현

- server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/WrapBookmark.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/MyPageBookmarkGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
* MyPage Bookmark 리스트 조회 테스트 코드 작성
* API 변경에 따른 Test 추가 작성
시큐리티와 RestDoc을 제외한 1차 테스트 코드 작성은 완료했습니다!
> test: bookmarkController Test 1차 완료

- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- 수락 대기중, 결제 대기중이 아닐 땐 유효하지 않은 접근 에러 처리
> refactor: eleteSuggest 과외 신청 취소 기능 예외처리 추가

- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
> test: deleteSuggest 과외 신청 취소 Test 코드 작성

- server/src/test/java/com/codueon/boostUp/domain/review/controller/MyPageReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPatchTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPostTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
* Review Delete 테스트 작성
* Review Edit 테스트 작성
* tabId가 Long 타입으로 되어있던 부분 수정
Review 테스팅 코드 1차 작성 완료
시큐리티 및 RestDoc 생성은 추후 작성할 예정입니다.
> test: reviewController 1차 테스팅 코드 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- acceptSuggest 과외 수락하기 기능 구현
controller 테스트는 통과되었으나 추후 Postman으로 테스트 필요....
> feat: acceptSuggest 과외 수락하기 기능 구현

- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- acceptSuggest 과외 수락하기 Test 코드 작성
> test: acceptSuggest 과외 수락하기 Test 코드 작성

- client/pages/index.tsx
- client/tailwind.config.js
* 반응형사이즈 (데스크탑, 테블릿, 모바일) tailwind.config.js에 반영
> feat: 반응형 사이즈 설정

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostReason.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Reason.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/ReasonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- declineSuggest 과외 거절하기
- Reason Entity 작성
- PostReason Dto 작성
> feat: declineSuggest 과외 거절하기 기능 구현 및 Reason 취소 사유 엔티티 작성

- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- declineSuggest 과외 거절하기 Test 코드 작성
> test: declineSuggest 과외 거절하기 Test 코드 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetSuggestInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- getSuggestInfo 결제 화면 조회 기능 구현
- SuggestDbService 수정
- SuggestDbService에 따른 Controller 수정
- Entity totalCost 추가
> feat: getSuggestInfo 결제 화면 조회 기능 구현 및 SuggestDbService 수정

- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- getSuggestInfo 결제 화면 조회 Test 코드 작성
- suggestDbService 수정에 따른 Test 코드 수정
> test: getSuggestInfo 결제 화면 조회 Test 코드 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- totalCost setter 메서드 추가
- totalCost = Math.abs(findLesson.getCost() * findSuggest.getQuantity());
> refactor: getSuggestInfo totalCost 로직 추가

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetTutorSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- Suggest 마이페이지 학생용 조회 시 lessonId 추가
- Teacher -> Tutor 변환
> refactor: lessonId 추가 및 Teacher -> Tutor 변환

- client/package.json
> feat: build명령어 설정

- .github/workflows/deploy.yml
> feat: FE자동배포 yml 파일 작성

- client/pages/index.tsx
> feat: 자동배포 확인용 문구

- client/pages/index.tsx
> feat: 자동배포 확인용 문구2

- client/package-lock.json
- client/package.json
- client/pages/login.tsx
- client/pages/resetPassword.tsx
- client/pages/signup.tsx
로그인, 회원가입, 비밀번호 재설정 페이지에 배경색을 설정했습니다
> feat:Login,signup,resetPassword페이지틀

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- acceptSuggest RequestBody DTO 수정
- acceptSuggest API lessonId 삭제
- declineSuggest API lessonId 삭제
- getSuggestInfo API lessonId 삭제
- API 변경에 따른 Service 수정
- API 변경에 따른 Test 코드 수정
> refactor: RequestBody DTO 수정 및 신청 프로세스 API lessonId 삭제

- server/src/main/java/com/codueon/boostUp/domain/suggest/pay/ReadyToPaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- 결제 PaymentInfo 저장 시 Suggest 정보 같이 저장
- getStudentSuggest tabId 2 조회 되도록 조건 and -> or 수정
> refactor: 결제 PaymentInfo 저장 시 Suggest 정보 같이 저장

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/CareerImage.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/AddressRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CareerImageRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CurriculumRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LanguageRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonAddressRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonInfoRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonLanguageRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/ProfileImageRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
- 과외 등록 기능 구현 완료
- 이미지 단건, 다중 처리
> feat: Lesson 등록 구현 완료

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- Lesson Controller postLesson @RequestPart 부분에 file,files 부분 각각 profileImage,careerImage로 변경
> refactor: Lesson Controller postLesson @RequestPart 부분에 file,files 부분 각각 profileImage,careerImage로 변경

- client/components/reuse/AuthBtn.tsx
- client/components/reuse/AuthContainer.tsx
- client/components/reuse/FormInputBox.tsx
- client/components/reuse/NewAuthBtn.tsx
- client/package-lock.json
- client/package.json
- client/pages/resetPassword.tsx
- client/tailwind.config.js
* AuthBtn : onClick 이벤트함수에 파라미터 선언
* AuthContainer : 모바일 버전 Width값 수정 + border round값 추가
* @hookform/error-message 라이브러리 추가
* negativeMessage, disabledBtnColor 색상코드 추가
* react-hook-form 사용 페이지 구현
* FormInputBox, NewAuthBtn 컴포넌트 추가 (현재까지 미사용)
> feat: resetPassword auth component 구현

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
> refactor: Lesson Controller 분리 작업

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/feign/KakaoPayFeignClient.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/pay/Amount.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/pay/CardInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/pay/PaySuccessInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/pay/RequestForPaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/PaymentInfoRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
- successPayment 결제 성공
- cancelPayment 결제 취소
- failedPayment 결제 실패
- endOfLesson 과외 종료
- 주석 추가
> feat: 결제 기능, 과외 종료 기능 구현 및 주석 추가

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- refactor: createLesson 리펙토링중
> refactor: createLesson 리펙토링중

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchContoller.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonAddress.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonLanguage.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/SearchService.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
* 과외 등록 시 LessonAddress에 id를 넣어 Cascade가 안되는 문제를 수정했습니다.
* LessonLanguage도 위와 동일합니다.
* 기타 저장 메서드를 분리해서 작성했습니다.
> refactor: 과외 등록 리팩터링 및 오류 수정

- client/pages/login.tsx
- client/pages/signup.tsx
로그인 페이지 회원가입 페이지의 인풋, 버튼, 에러메세지 등을 배치.
이후 서버로 데이터를 보내는 코드 추가 필요
> feat: 로그인회원가입퍼블리싱 #156

- client/pages/_app.tsx
> feat: 페이지 조립

- client/components/auth/ResetPwAuth.tsx
- client/components/auth/ResetPwSet.tsx
- client/pages/login.tsx
- client/pages/signup.tsx
> 검색창 제외한 모든 input 태그 rounded값 xl로 수정
- ResetPwAuth.tsx
- ResetPwSet.tsx
- signup.tsx
- login.tsx
> style: input태그 rounded값 xl로 수정

- client/styles/globals.css
> style: reset Css

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchContoller.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetTutorLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/SearchService.java
* 상세 검색 기능 추가
* 사용 언어 별 카테고리 검색 기능 추가
> feat: 카테고리 검색 및 상세 검색 구현

- client/components/reuse/CreateModalContainer.tsx
- client/pages/index.tsx
- client/styles/globals.css
- 글작성모달 컨테이너 구현
- global.css border:0 제거
> feat: createModal Container

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
* Controller 명 오타 및 주석 누락 수정
* 상세 검색 : 과외 타이틀 검색 조건 수정
> refactor: Lesson(Get) 검색 조건 및 Controller API 수정

- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetDetailPageLessonTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMainPageLessonTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/GetMyPageLessonTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/SearchControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
* Lesson 메인페이지(상세 검색, 언어별 검색, 홈페이지 조회) 조회 테스트 코드 작성
* Lesson 상세페이지(Lesson, LessonInfo, Curriculum) 조회 테스트 코드 작성
* MyPage Lesson(선생님 요약 정보 조회) 조회 테스트 코드 작성
* utils 패키지에 Test에 사용할 데이터를 메서드화했습니다. (DataForTest 클래스)
> test: Lesson 조회 기능 Controller 테스트 완료

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonDetailEdit.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
> feat: 과외 상세정보 수정 구현 완료

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
> feat: 과외 커리큘럼 수정 구현 완료

- server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonInfoRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
> feat: 과외 삭제 기능 구현

- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostAttemptFindPassword.java
- server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetAllDetailReviews.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
* 비밀번호 찾기(본인 확인) 기능 구현
* review division 0 error 수정
> feat: 비밀번호 재설정(본인 확인) 기능 구현

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
> feat:  과외 등록 이미지 S3에 업로드로 변경 구현

- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostChangePassword.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostEmail.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostName.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPassword.java
- server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
- server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberImage.java
- server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
* 회원 중복 검사 기능 구현
* 비밀번호 변경 기능 구현
> feat: 회원 중복 검사/비밀번호 변경 구현

- server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
* MemberController API 리팩토링
* AuthController API 리팩토링
> refactor: API 명세 변경으로 인한 MemberController API Refactoring

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- 변경된 API 명세에 따라 Lesson Controller API 수정
> refactor: Lesson 도메인 API 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/global/file/AwsS3Service.java
> feat: S3 과외 프로필 이미지 수정 구현

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/SearchController.java
SearchController API가 수정되었습니다.
**Postman URL 변경이 필요합니다.**
> refactor: searchController api URL 수정

- server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
Cors 이슈 발생으로 인해 SecurityConfig를 수정했습니다.
> refactor: Cors 이슈에 따른 SecurityConfig 설정 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
> feat: 과외 삭제 시 S3에 이미지 삭제 구현

- client/components/createModal/BasicInfo.tsx
- client/pages/basicInfo.tsx
- client/pages/index.tsx
- client/pages/signup.tsx
> feat : 기본정보 입력 페이지 #203

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- getPaymentReceipt 결제 영수증 조회 기능 구현
- Payment Entity paymentNumber 필드 추가
- Suggest Entity paymentMethod 필드 추가
- 마이페이지 선생님 조회 시 조건 수정
- 결제 영수증 조회 및 결제 페이지 조회 시 예외처리
> feat: getPaymentReceipt 결제 영수증 조회 기능 구현 및 선생님 마이페이지 조회 조건 수정

- client/components/carousel/Carouselcomp.tsx
- client/pages/index.tsx
> fix: 캐러셀 resizing

- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- Suggest 영수증 조회 Test 코드 작성
- Suggest Get 리팩토링
> test: Suggest 영수증 조회 Test 코드 작성 및 Suggest Get 리팩토링

- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- 결제 요청 시 불필요한 PayNumber 저장 로직 제거
- 결제 성공 시 PaymentMethod 저장 방식 변경
- PaymentInfo Entity PayNumber 제거
- 예외 처리 추가
> refactor: 불필요한 PayNember 제거 및 PaymentMethod 저장 방식 변경

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
- server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetailService.java
- server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetails.java
- server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
- server/src/main/java/com/codueon/boostUp/global/security/provider/JwtAuthenticationProvider.java
- server/src/main/java/com/codueon/boostUp/global/security/token/JwtAuthenticationToken.java
- server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
로그인 기능 구현 - 완료
Redis, 보안 - 수정 필요
> feat : 로그인 기능 구현

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- getLessonAttendance 출석부 조회 기능 구현
- lessonAttendanceCheck 출석 인정 기능 구현
- lessonAttendanceCancel 출석 인정 취소 기능 구현
- getLessonAttendance 반환 데이터 변경
- 출석부 하루에 한 번만 인정 가능하도록 수정
> feat: 출석부 조회/출석인정/출석인정취소 기능 구현

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetLessonAttendance.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- 출석부 조회 응답 DTO GetLessonAttendance 추가
수업 신청 횟수 quantity, 출석 인정 횟수 quantityCount, 진행률 progress
- quantityCount 0에서 시작하여 출석 인정 시 `quantityCount+=1`, 출석 인정 취소 시 `quantityCount-=1` 로 변경
(기존: quantityCount = quantity 출석 인정 시 `quantityCount-=1`, 출석 인정 취소 시 `quantityCount+=1` )
> refactor: 출석부 조회 시 Response 데이터 변경

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonTest.java
- 과외 등록 테스트 작성
- 추후에 액세스 토큰과 리프레시 토큰이 구현되면 리펙터링 예정입니다.
> test: 과외 등록 테스트 작성

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/feign/TossPayFeignClient.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/toss/CancelToTossPaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/toss/Cancels.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/toss/TossPayCancelInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/utils/PayConstants.java
> feat: Toss 환불 기능 구현

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- 출석부 조회 Test 코드 작성
- 출석 인정 Test 코드 작성
- 출석 인정 취소 Test 코드 작성
> test: 출석부 조회/출석인정/출석인정취소 Test 코드 작성

- server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
- server/src/main/java/com/codueon/boostUp/domain/member/entity/AccountStatus.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
- server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
- server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
- server/src/main/java/com/codueon/boostUp/global/utils/RedisUtils.java
> feat : 로그아웃 기능 구현

- server/src/asciidoc/index.adoc
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/UpdateLessonTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- 과외 요악 정보 수정 테스트
- 고외 요약 정보 수정 restDocs 문서 자동화 적용
> test: 과외 요약 수정 테스트 & restDocs 문서 자동화

- server/src/asciidoc/index.adoc
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLessonDetailEdit.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonDetailEditTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonInfoEditTest.java
- 과외 상세 수정 테스트
- restDocs 문서 자동화
> test: 과외 상세 수정 테스트 & restDocs 문서 자동화

- server/src/asciidoc/index.adoc
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/DeleteLessonTest.java
- 과외 삭제 테스트 작성
- 과외 삭제 restDocs 문서 자동화 작성
> test : 과외 삭제  테스트 & 문서 자동화

- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Suggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayCancelInfo.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
- Suggest 모든 테스트 Spring Rest Docs 적용
- Response 데이터 공통화
- Suggest 생성자에 totalCost 및 PaymentMethod
- DataForTest util Suggest 데이터 수정
> test: Suggest Test Rest Docs 적용

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/PostLesson.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/PostLessonTest.java
- PostLesson 리팩터링 (lessonId 삭제)
> refactor: lesson dto 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
- server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberImage.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestPostTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
- Suggest authentication 토큰 리펙토링
- Test authentication 적용
- Member 수정 반환데이터 생성
> refactor: Suggest authentication 토큰 리펙토링 및 Member 수정 반환데이터 생성

- server/.gitignore
- server/Dockerfile
- server/build.gradle
- server/src/main/java/com/codueon/boostUp/global/actuator/HealthCheck.java
- server/src/main/resources/application.yml
* Jenkins Server - EC2 Server Domain(HTTPS) 연결
* Jenkins - Docker 환경 구축
* Jenkins - Github CI 환경 구축(Github WebHooks)
* EC2 Nginx Server 환경 구축
* 쉘 스크립트 파일 작성
* RDS 데이터베이스 테이블 생성
* EC2 원격 접속 환경 구축
* AWS Parameter Store 등록
* Spring Boot Health Check 컨트롤러 추가
> feat: AWS EC2 서버 구축

- server/build.gradle
- server/src/main/resources/application-server.yml
> refactor: build.gradle queryDsl 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
> refactor: lesson 수정  리팩터링 중

- server/build.gradle
- server/src/main/resources/application-server.yml
* build.gradle aws parameter store dependency 누락 수정
> refactor: build.gradle aws parameter store dependency 추가

- server/build.gradle
> fix: aws parameter store dependency 충돌 수정

- server/src/main/resources/static/index.html
- server/src/main/resources/static/scripts.js
> refactor: 실수로 지워진 static폴더 복구

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/domain/member/repository/MemberRepository.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
- server/src/main/resources/application.yml
- 과외 등록 시 한 멤버당 하나의 과외만 등록 가능하게 리팩터링
> refactor: 과외 등록 시 한 멤버당 하나의 과외만 등록 가능하게 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- 과외 토큰 부분 리팩터링 Token.getId -> memberId)
> refactor : lesson 토큰 부분 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
##변경 사항
- lesson 로컬에서 이미지 수정 리팩터링
> refactor : lesson 로컬 이미지 수정 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetQuantityCount.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetRefundPayment.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
#400 
- Suggest API 주소 수정
- lesson.getName()->member.getName() 수정
- QueryDSL member 삼중조인 수정
- Suggest 반환 데이터 수정
> refactor: lesson.getName()->member.getName() 수정 및 Suggest 반환 데이터 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/WrapUrl.java
- 마이페이지 등록한 과외 조회 시 url만 나오던 것 lessonUrl로 랩핑
> refactor : 마이페이지 등록한 과외 조회 url 랩핑 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- 과외 수정 시(과외 요약, 과외 상세) 해당 멤버만 수정할 수 있는 로직 추가
> refactor : 과외 수정 시 해당 멤버만 수정할 수 있는 로직 추가

- server/Dockerfile
- server/src/main/resources/bootstrap.yml
Parameter store 연동을 위한 gradle 파일 수정
> refactor: parameter store gradle 수정

- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
> refactor: review Test 수정

- server/build.gradle
- server/src/main/resources/application.yml
> refactor: server 재발돼라

- server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkCreateTest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewPatchTest.java
- Review, Bookmark API 주소 수정
- Review authentication
- Bookmark authentication
- lesson Service 예외처리
- lesson.getName() -> member.getName() 수정
> refactor: Review, Bookmark authentication 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
> refactor : lessonService 리팩터링

- server/build.gradle
- server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
- server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
- server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetailService.java
- server/src/main/java/com/codueon/boostUp/global/security/details/MemberDetails.java
- server/src/main/java/com/codueon/boostUp/global/security/details/OAuth2DetailService.java
- server/src/main/java/com/codueon/boostUp/global/security/dto/ClaimsVO.java
- server/src/main/java/com/codueon/boostUp/global/security/filter/JwtVerificationFilter.java
- server/src/main/java/com/codueon/boostUp/global/security/handler/OAuth2FailureHandler.java
- server/src/main/java/com/codueon/boostUp/global/security/handler/OAuth2SuccessHandler.java
- server/src/main/java/com/codueon/boostUp/global/security/oauth/OAuth2Attribute.java
- server/src/main/java/com/codueon/boostUp/global/security/provider/JwtAuthenticationProvider.java
- server/src/main/java/com/codueon/boostUp/global/security/token/JwtAuthenticationToken.java
- server/src/main/java/com/codueon/boostUp/global/security/utils/AuthConstants.java
- server/src/main/java/com/codueon/boostUp/global/security/utils/JwtTokenUtils.java
- server/src/main/java/com/codueon/boostUp/global/utils/RedisUtils.java
> feat: JWT 토큰 재발급 구현

- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
Authentication에 만료 여부와 accessToken 정보가 추가되어 해당 정보를 Test에 추가했습니다.
> refactor: Authentication 변경에 따른 Token 정보 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetMainPageLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetTutorLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
-  lesson에 name 제거 하면서  전반적인 리팩터링
> refactor : lesson에 name 제거 하면서  전반적인 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/domain/member/entity/Member.java
- server/src/main/java/com/codueon/boostUp/domain/member/entity/MemberImage.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReview.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/GetReviewMyPage.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/resources/application-prod.yml
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
* 리뷰 관련 N+1 문제를 수정했습니다.
* MemberImage와 ProfileImage 정보를 Embedded 타입으로 변경했습니다.
* 리뷰 관련 테스트 수정했습니다.
**📌 테이블이 변경되어 관련 테스트를 수정해야합니다.**
> refactor: Review N+1 문제 해결

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- Suggest 마이페이지 조회 query 수정
- Suggest 단건 조회 QueryDSL 추가
> refactor: 조회 query 수정 및 Suggest 단건 조회 QueryDSL 추가

- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
> refactor: review 버그 픽스

- server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
> refactor : 북마크 N+1 관련 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/GetLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- LessonRepository 과외 상세페이지 요약 정보 where절 추가, select member 객체전부가 아닌 name으로 변경
> refactor : 과외 상세페이지 요약 정보 조회 리팩터링

- server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
* Lesson과 Member가 잘못 조인되던 부분을 수정했습니다.
* Test용 저장과 S3 저장 API를 구분하였습니다. (엔드포인트 : /lesson/test)
> refactor: Lesson 쿼리 수정

- server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
- server/src/main/java/com/codueon/boostUp/global/handler/StompHandler.java
- server/src/main/resources/static/index.html
- server/src/main/resources/static/scripts.js
RedisConfig.class 설정 변경
환경에 따라 주석 바꾸시면 됩니다!
> refactor: redis config 임시 분리

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetLessonCurriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetLessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetMainPageLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetStudentLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetTutorLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetTutorMypageLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PatchLessonCurriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonDetailEdit.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonImage.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonInfoEdit.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/etc/CareerImageVO.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/etc/WrapUrl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPatchTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
> refactor : 과외 dto 폴더 정리

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentReceipt.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetRefundPayment.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
- server/src/test/java/com/codueon/boostUp/domain/review/controller/ReviewGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- Suggest 한 과외 당 한 번만 신청 가능하도록 중복 등록 방지 메서드 추가
- Kakao 결제 요청 시 토큰 없이도 요청 가능하도록 로직 삭제
- ExceptionCode 추가
- 필요없는 Member 객체 조회 삭제
- tutohName -> name 수정
> refactor: Suggest 중복 등록 방지 메서드 추가 및 Suggest 수정

- client/components/createModal/BasicInfo.tsx
- client/components/detailComp/DetailBasicInfo.tsx
- client/components/detailComp/DetailBasicInfoEditModal.tsx
- client/components/reuse/container/CreateModalContainer.tsx
- client/components/reuse/container/ModalBackDrop.tsx
- client/pages/detail/[id].tsx
- 상세페이지 요약정보 수정모달 defaultValue값 반영완료
- 상세페이지 요약정보 수정모달 ON/OFF 구현완료
> feat: 상세페이지 요약정보 수정모달 api제외 구현완료

- client/apis/detail/getDetailReview.tsx
- client/atoms/detail/detailAtom.tsx
- client/components/createModal/BasicInfo.tsx
- client/components/createModal/Curriculum.tsx
- client/components/createModal/WriteModal.tsx
- client/components/detailComp/DetailBasicInfo.tsx
- client/components/detailComp/DetailReview.tsx
- client/hooks/detail/useGetDetailReview.tsx
- client/pages/detail/[id].tsx
- 과외후기 구현완료
- 기본정보 수정 시 editmode를 통해 수정여부 판단
> feat: 상세페이지 과외후기 구현완료

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/WrapPaymentStatusCheck.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/WrapQuantityCount.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PaymentInfo.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Purchase.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/PurchaseStatus.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Ticket.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/PurchaseRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
- server/src/main/resources/db/h2/Ticket.sql
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
- 결제 여부 조회 메서드
- 이용권 설계 및 1차 구현
> feat: 결제 여부 조회 메서드 구현 및 이용권 1차 구현

- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
- 사용자 프로필 수정 시 디폴트 이미지를 제외한 기존 S3 이미지 삭제
> refactor: 사용자 프로필 수정 시 디폴트 이미지를 제외한 기존 S3 이미지 삭제

- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Get/GetMainPageLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Purchase.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/entity/Ticket.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/TicketRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/resources/db/h2/Ticket.sql
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
- 이용권 구매 시 ticketId로 정렬
- member 이미지 수정 로컬로 변경
- test 수정
> feat: 이용권 구현 2 - 이용권 구매 시 정렬

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
#459 
- 학생 신청 내역 삭제 예외처리 수정
- Suggest Controller 주석 추가
> refactor: 학생 신청 내역 삭제 예외처리 수정

- client/apis/detail/getBasicInfo.tsx
- client/apis/mypage/deleteApply.tsx
- client/apis/mypage/getMyTutor.tsx
- client/apis/mypage/getStudentInfo.tsx
- client/apis/mypage/getTutorInfo.tsx
- client/apis/mypage/postAccept.tsx
- client/atoms/main/mainAtom.tsx
- client/components/Detail/ApplyModal.tsx
- client/components/Detail/DetailButtons.tsx
- client/components/Maincard/Card.tsx
- client/components/Mypage/AcceptModal.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/StudentClass.tsx
- client/components/Mypage/StudentReview.tsx
- client/components/createModal/BasicInfo.tsx
- client/hooks/detail/useGetBookmarkModi.tsx
- client/hooks/mypage/useDeleteApply.tsx
- client/hooks/mypage/useGetMyTutor.tsx
- client/hooks/mypage/useGetStudentInfo.tsx
- client/hooks/mypage/useGetTutorInfo.tsx
- client/hooks/mypage/usePostAccept.tsx
- client/pages/detail/[id].tsx
- client/pages/mypage/[name].tsx
메인화면 카드 정보 Atom생성
마이페이지 학생용탭 수강내역 렌더링 및 신청취소 구현
상세페이지 과외삭제하기 기능 수정
과외 수락 모달 추가
> feat 마이페이지 기능 추가

- client/hooks/shop/useGetKakaoNTossPay.tsx
- client/hooks/shop/useGetPaymentCheck.tsx
- client/hooks/shop/useGetPaymentInfo.tsx
- client/hooks/shop/useGetReceipt.tsx
> fix: tanstack query import 문으로 대체

- client/components/Maincard/Card.tsx
- client/hooks/mypage/useDeleteApply.tsx
- client/hooks/mypage/useGetStudentInfo.tsx
- client/hooks/mypage/useGetTutorInfo.tsx
- client/hooks/mypage/usePostAccept.tsx
> fix : React-Query-tanstack

- client/atoms/main/mainAtom.tsx
- client/components/Maincard/Card.tsx
- client/components/Maincard/Cards.tsx
- client/components/filter/MobileLanguageFilter.tsx
- client/hooks/board/useGetFilteredBoard.tsx
- api요청을 통해 받아온 필터링된 데이터를 mainAtom의 mainCardInfo 전역상태에 연결
- card컴포넌트에 recoil 상태로 데이터 매핑작업 수정
> refactor: 메인페이지 언어필터기능 연결완료

- client/apis/detail/deleteDetail.tsx
- client/apis/mypage/getCloseClass.tsx
- client/apis/mypage/getMyTutor.tsx
- client/components/Detail/ApplyModal.tsx
- client/components/Detail/DetailButtons.tsx
- client/components/Header/Header.tsx
- client/components/Maincard/Card.tsx
- client/components/Mypage/AcceptModal.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/ClassList.tsx
- client/components/Mypage/MypageInfo.tsx
- client/components/Mypage/StudentClass.tsx
- client/hooks/mypage/useGetCloseClass.tsx
- client/hooks/mypage/useGetMyTutor.tsx
- client/hooks/mypage/useGetTutorInfo.tsx
- client/pages/lesson/[id].tsx
- client/pages/mypage/[name].tsx
나의과외로가기버튼 구현 
나의 과외삭제버튼 수정
선생님 탭에서 수락내역, 수락요청, 과외종료 버튼 구현
> Feat/my page teacher tab#513

- client/components/Mypage/MypageInfo.tsx
useEffect를 이용해서 기본 정보 데이터 호출시 생기는 에러를 수정했습니다.
> featMypageInfo기본정보호출수정

- server/src/main/java/com/codueon/boostUp/global/file/FileHandler.java
> refactor : 경력 이미지도 로컬에서 저장 시 uuid 적용

- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewDbService.java
> refactor: Member Controller Token 수정

- server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
WebSocket CORS 이슈로 인한 Origin 등록
> fix: websocket CORS 이슈 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Patch/PostLessonInfoEdit.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/Post/PostSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostAttemptFindPassword.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostEmail.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostLogin.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostMember.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostName.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPassword.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPasswordInLoginPage.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/PostPasswordInMyPage.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/controller/ReviewController.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PatchReview.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/dto/PostReview.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostPaymentUrl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostReason.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/PostSuggest.java
- 도메인별 유효성 검사 추가
- Controller `@Valid` 추가
> feat: 유효성 검사 추가

- server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
- server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
- server/src/main/resources/static/scripts.js
- server/src/test/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
- server/src/test/java/com/codueon/boostUp/domain/member/controller/MemberControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
> refactor: 북마크 dto 수정(career, company)

- server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatController.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/PostMessage.java
- server/src/main/java/com/codueon/boostUp/domain/chat/dto/RedisChat.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/AuthDto.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
회원 별 채팅방 구독 기능 구현
AuthDto 필드 수정
> feat: 회원 별 채팅방 구독  기능 구현

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonTestController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLessonCurriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetMainPageLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetStudentLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetTutorLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetTutorMypageLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PatchLessonCurriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PostLessonDetailEdit.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PostLessonImage.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/patch/PostLessonInfoEdit.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/post/PostLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/post/PostSearchLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/utils/CareerImageVO.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/utils/WrapUrl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Lesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/global/file/AwsS3Service.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPatchTest.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonPostTest.java
- 경력 이미지 따로 보내지 않을 때 null처리 , lesson DTO 패키지명 변경, lessonInfo name 삭제
> refactor: 과외 경력 이미지 리팩터링, 패키지 수정

- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/resources/application-prod.yml
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/TossPaymentTest.java
- Toss 결제 requestUrl 이슈 해결
- Kakao 결제 requestUrl 이슈 해결
> refactor: requestUrl 이슈 해결

- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewService.java
> refactor: 리뷰 쿼리 문제 수정

- server/src/main/java/com/codueon/boostUp/global/handler/StompHandler.java
> refactor: Stomp 핸들러 수정

- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetStudentSuggest.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- 학생 과외 신청 내역 조회 시 리뷰 여부 데이터 추가
> refactor: 학생 과외 신청 내역 조회 시 리뷰 여부 데이터 추가

- client/.env
- client/apis/mypage/deleteFinishedClass.tsx
- client/components/Mypage/StudentBookmark.tsx
- client/components/Mypage/StudentClass.tsx
- client/components/Mypage/StudentReview.tsx
- client/hooks/main/useGetMainCard.tsx
- client/hooks/mypage/useDeleteFinishedClass.tsx
- client/hooks/mypage/useGetStudentInfo.tsx
- client/tsconfig.json
마이페이지 학생용탭 수강내역에서 후기를 쓴 학생은 후기 작성 버튼이 안보이게 구현
과외 종료된 학생이 과외 내역을 삭제 할 수 있게 구현
> feat 마이페이지 수강내역 기능 추가

- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/ClassList.tsx
- client/components/Mypage/EditUserData.tsx
- client/components/Mypage/EditUserPwd.tsx
- client/components/Mypage/FinishedClass.tsx
- client/components/Mypage/MypageInfo.tsx
- client/components/reuse/btn/MypageTabBtn.tsx
마이페이지의 비밀번호 변경, 개인정보 수정 모달 CSS 변경
마이페이지 탭이 모바일 환경에서 깨지는 현상 수정
> feat 마이페이지 스타일 수정

- client/components/Header/Header.tsx
- client/components/Header/SearchPop.tsx
- client/components/detailComp/MobileDetailBasicInfo.tsx
- client/components/filter/MobileLanguageFilter.tsx
- client/hooks/main/usePostWrite.tsx
이슈 #567 
[검색창]
[상세페이지]
[모바일 필터]
[모달]
> Refactor/things#567 리펙토링 진행상황

- server/src/main/java/com/codueon/boostUp/domain/member/controller/MemberController.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/GetMemberEditInfo.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberService.java
- 회원 정보 수정 메서드 로컬/S3 분리
- 회원 정보 수정 시 반환 데이터 추가
> refactor: 회원 정보 수정 메서드 로컬/S3 분리

- server/src/main/java/com/codueon/boostUp/domain/chat/dto/GetAlarmMessage.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/SendAlarmService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/SendMessageService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/utils/RedisSubscriber.java
- server/src/main/java/com/codueon/boostUp/global/config/RedisConfig.java
- server/src/main/java/com/codueon/boostUp/global/config/WebSocketConfig.java
- server/src/main/java/com/codueon/boostUp/global/security/token/JwtAuthenticationToken.java
- server/src/main/resources/static/scripts.js
> fix: 채팅 알람 기능 오류 수정

- client/apis/mypage/deleteAccount.tsx
- client/apis/mypage/deleteFinishedClass.tsx
- client/apis/mypage/deleteReview.tsx
- client/components/Maincard/Card.tsx
- client/components/Maincard/Cards.tsx
- client/components/Maincard/Pagination.tsx
- client/components/Mypage/AcceptModal.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/ClassList.tsx
- client/components/Mypage/FinishedTutor.tsx
- client/components/Mypage/MypageInfo.tsx
- client/components/Mypage/StudentClass.tsx
- client/components/Mypage/StudentReview.tsx
- client/components/Mypage/TeacherTab.tsx
- client/hooks/mypage/useDeleteAccount.tsx
- client/hooks/mypage/useDeleteFinishedTutor.tsx
- client/hooks/mypage/useDeleteReview.tsx
- client/hooks/mypage/useGetMyTutor.tsx
- client/hooks/mypage/useGetStudentInfo.tsx
- client/pages/mypage/[name].tsx
- client/styles/globals.css
메인 페이지에 페이지 네이션을 추가했습니다 
탈퇴, 과외삭제 버튼을 추가했습니다 (탈퇴버튼 기능은 백엔드 작업 중)
> feat 메인페이지 페이지네이션 추가

- client/apis/chat/getResetChatAlarm.tsx
- client/atoms/chat/chatAtom.tsx
- client/components/chat/ChatComp.tsx
- client/components/chat/ChatContainer.tsx
- client/components/chat/ChatListComp.tsx
- client/components/chat/ChatListContent.tsx
- client/components/chat/ChatReceiveMessage.tsx
- client/components/chat/ChatSendMessage.tsx
- client/hooks/chat/socket.tsx
- client/hooks/chat/useGetChatList.tsx
- client/hooks/chat/useGetChatRoomList.tsx
- client/hooks/chat/useGetResetChatAlarm.tsx
- client/hooks/chat/useTranslateTime.tsx
- client/pages/chat/[memberId].tsx
- 시간코드 변환 custom hook 구현
- chatroom subscribe 구현
- 업데이트 된 채팅방 데이터를 받았을 경우, 기존 데이터를 제거하고 상단에 넣어주는 알고리즘 구현
- alarmcount 초기화 api연결
> fix: 채팅방 연동 이슈 해결

- client/apis/mypage/deleteAccount.tsx
- client/apis/mypage/deleteApply.tsx
- client/apis/mypage/deleteReview.tsx
- client/apis/mypage/getAllBookmark.tsx
- client/apis/mypage/getCloseClass.tsx
- client/apis/mypage/getMyReview.tsx
- client/apis/mypage/getMyTutor.tsx
- client/apis/mypage/getStudentInfo.tsx
- client/apis/mypage/getTutorInfo.tsx
- client/apis/mypage/postAccept.tsx
- client/apis/mypage/postReview.tsx
- client/components/Detail/DetailButtons.tsx
- client/components/Maincard/Card.tsx
- client/components/Maincard/Pagination.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/FinishedTutor.tsx
- client/components/Mypage/StudentBookmark.tsx
- client/components/Mypage/StudentClass.tsx
- client/components/reuse/container/DetailContentContainer.tsx
- client/pages/mypage/[name].tsx
- client/styles/globals.css
과외 상세보기에서 진행방식 내용을 가운데에서 위로 이동시켰습니다
마이페이지의 학생 탭에서 채팅하기를 누르면 해당 과외의 채팅방이 생성되어 선생님과 연결 됩니다.
> feat 마이페이지 학생탭 채팅하기 연결

- client/atoms/main/mainAtom.tsx
- client/components/Detail/DetailButtons.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/ClassList.tsx
- client/components/Mypage/FinishedTutor.tsx
- client/components/Mypage/ReviewEditModal.tsx
- client/components/Mypage/StudentBookmark.tsx
- client/components/Mypage/StudentClass.tsx
- client/components/Mypage/StudentReview.tsx
- client/components/Navbar/Navbar.tsx
- client/components/detailComp/DetailReview.tsx
- 마이페이지 나의 후기 수정모달 퍼블리싱
- 마이페이지 각 탭별 min-width값 설정 및 데이터가 없을 경우 부합하는 텍스트 표시
- 나의 후기 컴포넌트 수정
> feat : 과외후기 수정모달 구현

- client/components/chat/ChatComp.tsx
- client/components/chat/ChatContent.tsx
- client/components/chat/ChatListComp.tsx
- client/components/chat/ChatNoticeMessage.tsx
- client/components/filter/LanguageFilter.tsx
- client/components/filter/MobileLanguageFilter.tsx
- client/hooks/chat/socket.tsx
- client/hooks/chat/useTranslateTime.tsx
- client/pages/chat/[memberId].tsx
- 업데이트 된 메시지가 있을 경우, 새로 받아온 데이터의 receiveId가 아닌 기존의 receiveId로 전역상태에 할당
- messageType이 ALARM일 경우 알람 컴포넌트로 출력
> fix: 실시간채팅 버그 개선

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/dto/get/GetLesson.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/test/java/com/codueon/boostUp/domain/lesson/controller/LessonGetTest.java
> refactor: getLesson editable 안나오던 부분 수정

- server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
> refactor: 로그아웃  안되던 부분 수정

- client/components/chat/ChatNoticeMessage.tsx
- client/components/detailComp/DetailBasicInfo.tsx
- client/pages/chat/[memberId].tsx
- client/pages/signup.tsx
- 닉네임 정규표현식 5글자 이상에서 3글자 이상으로 수정
- subscribe 실행시간 2초에서 5초로 수정
> fix: nickname regex 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
> refactor: 과외 조회 수정

- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
> refactor: LessonInfo 수정

- server/src/main/java/com/codueon/boostUp/domain/bookmark/controller/BookmarkController.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/service/BookmarkService.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
> refactor: 북마크 리팩토링

- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
> refactor: 메인페이지 북마크 조회 안되던 부분 수정

- client/apis/detail/postApply.tsx
- client/apis/detail/postCurModi.tsx
- client/apis/main/postSearch.tsx
- client/apis/main/postWrite.tsx
- client/apis/mypage/getAllBookmark.tsx
- client/apis/mypage/postAccept.tsx
- client/apis/mypage/postDecline.tsx
- client/apis/mypage/postReview.tsx
- client/components/Maincard/Card.tsx
- client/components/createModal/BasicInfo.tsx
- client/components/createModal/Curriculum.tsx
- client/components/detailComp/DetailBasicInfo.tsx
- client/components/detailComp/DetailExtra.tsx
- client/hooks/auth/usePostLogin.tsx
- client/hooks/detail/useGetCurriculum.tsx
- client/hooks/detail/useGetDetailReview.tsx
- client/hooks/detail/useGetExtra.tsx
- client/hooks/main/usePostWrite.tsx
- client/pages/shop/[id]/receipt.tsx
- 불필요 console.log 삭제 
- main화면 불필요 bookmark 통신 삭제
> Refactor/things#567 리펙토링

- client/components/Maincard/Card.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/DeclineModal.tsx
- client/components/Mypage/StudentReview.tsx
- client/components/createModal/BasicInfo.tsx
- client/hooks/detail/useGetBookmark.tsx
- client/hooks/detail/useGetBookmarkModi.tsx
- client/hooks/detail/usePostApply.tsx
- client/hooks/main/useGetMainCard.tsx
- client/hooks/mypage/useDeleteFinishedTutor.tsx
- client/hooks/mypage/useGetAllBookmark.tsx
- client/hooks/mypage/useGetCloseClass.tsx
- client/hooks/mypage/useGetMyTutor.tsx
- client/hooks/mypage/useGetStudentInfo.tsx
- client/hooks/mypage/usePostAccept.tsx
- client/hooks/mypage/usePostDecline.tsx
- client/hooks/mypage/usePostReview.tsx
- client/pages/login.tsx
- client/pages/mypage/[name].tsx
후기 삭제버튼을 서버와 연결해 기능이 구현 되는 것을 확인했습니다. 
모바인 로그인 페이지에서 하단 링크 글씨가 두줄이 되는 것을 막기 위해 폰트 크기를 줄였습니다. 
메인 페이지의 카드 부분의 이미지는 클릭해도 상세 페이지로 넘어가지 않게 코드를 다시 바꿨습니다.(북마크 기능과 겹치지 않도록)
메인 페이지에서 재직 회사의 글자 수로 카드의 크기가 넘치지 않게 글자수를 제한했습니다 (18자)
> Feat 후기삭제서버 연결 

- client/apis/mypage/patchReview.tsx
- client/atoms/chat/chatAtom.tsx
- client/atoms/mypage/myPageAtom.tsx
- client/components/Mypage/ReviewEditModal.tsx
- client/components/Mypage/StudentReview.tsx
- client/components/chat/ChatContent.tsx
- client/components/chat/DesktopChatComp.tsx
- client/hooks/mypage/usePatchReview.tsx
- client/pages/index.tsx
- client/pages/mypage/[name].tsx
- 채팅페이지 active 상태변화 이슈 해결
- 리뷰 수정모달 기능 구현 완료
> fix : 채팅페이지 active상태변화 이슈 해결

- server/src/main/java/com/codueon/boostUp/domain/lesson/controller/LessonController.java
lesson Controller updateLesson lessonId 순서 변경
> refactor : updateLesson lessonId 순서 리팩터링

- client/components/Maincard/Card.tsx
- client/components/Mypage/MypageInfo.tsx
- client/pages/mypage/[name].tsx
메인페이지에서 같은 수업의 북마크를 두번 이상 누를 수 없던 기능을 수정했습니다. 
같은 수업의 북마크를 여러번 눌러도 정상 작동합니다.  
마이페이지의 상단 비밀번호변경, 회원탈퇴 버튼이 모바일 화면에서 깨지는 것을 수정했습니다. 
수업을 등록하지 않은 유저는 선생님 탭에서 빈화면 대신 안내 문구를 보도록 수정했습니다.
> feat 북마크 이중 클릭 가능

- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/CustomLessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/KakaoPayController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/PaymentController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/TossPayController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/KakaoPayService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/PaymentService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/TossPayService.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestGetTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPayControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPaymentTest.java
Controller 및 Service 분리 후 Test 코드 수정
- suggest
- payment
- kakaoPay
- TossPay
> refactor: suggestController 분리

- server/src/asciidoc/index.adoc
- server/src/test/java/com/codueon/boostUp/domain/suggest/contoller/SuggestDeleteTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPayControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/kakao/KakaoPaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPayControllerTest.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/toss/TossPaymentTest.java
- suggest 테스트 추가
- suggest 테스트 Rest Docs 추가
> test: Suggest Rest Docs Test 코드 추가

- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepository.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonDbService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/service/LessonService.java
- server/src/main/java/com/codueon/boostUp/domain/member/dto/AuthDto.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
> refactor : 로그인 시 등록한 과외 여부 추가

- client/apis/auth/getGoogleLogin.tsx
- client/apis/auth/getKakaoLogin.tsx
- client/apis/detail/postApply.tsx
- client/components/Detail/ApplyModal.tsx
- client/components/Mypage/AcceptModal.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/ClassList.tsx
- client/components/Mypage/FinishedTutor.tsx
- client/components/createModal/BasicInfo.tsx
- client/components/createModal/ExtraInfo.tsx
- client/hooks/auth/useGetGoogleLogin.tsx
- client/hooks/auth/useGetKakaoLogin.tsx
- client/hooks/detail/usePostApply.tsx
- client/pages/login.tsx
수락하기 버튼 작동하도록 코드 변경했습니다. 
신청하기 요청사항이 필수에서 선택으로 바뀌었습니다. 
선생님 탭에서 font를 통일 했습니다. 
과외 등록시 재직 회사의 placeholder의 내용을 예시로 바꾸었습니다.
> feat 신청하기 요청사항 수정

- client/components/Maincard/Card.tsx
- client/components/detailComp/DetailExtra.tsx
> style: 상세페이지 참고사진 리사이징

- client/atoms/main/mainAtom.tsx
- client/atoms/mypage/myPageAtom.tsx
- client/components/Maincard/Card.tsx
- client/components/Maincard/Pagination.tsx
- client/components/filter/LanguageFilter.tsx
- client/hooks/board/useGetFilteredBoard.tsx
- client/package-lock.json
- client/package.json
- client/pages/_app.tsx
- client/pages/api/auth/[...nextauth].ts
페이지네이션이 언어 필터 적용시 연동되지 않는 부분을 수정했습니다. 
oauth 시도 중인데 아직 덜 마무리 되었습니다. 이후 작업해서 pr올리겠습니다. 
**pull 받고 한번 npm i 해주세요**
> feat 페이지네이션 수정

- server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
- server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRegisterController.java
- server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatMessage.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/EventMessageService.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/MemberDbService.java
- server/src/main/java/com/codueon/boostUp/global/exception/ExceptionCode.java
- server/src/main/java/com/codueon/boostUp/global/handler/StompHandler.java
- server/src/main/resources/application-prod.yml
- server/src/test/java/com/codueon/boostUp/domain/chat/ChattingFullTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/utils/StompFrameHandlerImpl.java
- server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
> refactor: edit Lesson 수정

- server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
> refactor: 프론트 배포 주소 변경에 따른 Origin 수정

- client/next.config.js
> Client ssr: CORS 설정 test

- server/src/main/java/com/codueon/boostUp/domain/lesson/repository/LessonRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/PaymentController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/contoller/SuggestController.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetPaymentStatusCheck.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetQuantityCount.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/dto/GetRefundPayment.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/CustomSuggestRepository.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/repository/SuggestRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/FeignService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/KakaoPayService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/PaymentService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestDbService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/SuggestService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/service/TossPayService.java
- server/src/main/java/com/codueon/boostUp/domain/suggest/utils/SuggestConstants.java
- server/src/test/java/com/codueon/boostUp/domain/suggest/payment/PaymentTest.java
- 과외 신청한 사용자 닉네임 조회 메서드 추가
- Wrap~ DTO -> Get~ DTO 로 수정
- 주석 수정 및 통일
> refactor: Suggest 리팩토링 및 코드 정리

- client/next.config.js
> chore: removeImports 삭제 테스트

- client/components/Detail/ApplyModal.tsx
- client/components/auth/ResetPwEmailAuth.tsx
- client/components/auth/ResetPwSet.tsx
- client/components/createModal/BasicInfo.tsx
- client/components/detailComp/DetailExtra.tsx
- client/hooks/auth/usePostEmailAuth.tsx
- client/pages/index.tsx
- client/pages/resetPassword.tsx
- 필터 컴포넌트 반응형 기준 764px -> 1024px로 변경
- input 중 중복체크 부분 3개 이하로 선택할 수 있도록 limit setting
- 비밀번호 재설정 페이지 unmount시 각 상태 초기화 로직 추가
> fix : filterComp Resizing / set input limit / resetPassword refactoring

- client/next.config.js
> chore: next config 배포 성공 환경으로 변경

- server/src/main/java/com/codueon/boostUp/domain/member/controller/AuthController.java
- server/src/main/java/com/codueon/boostUp/domain/member/service/AuthService.java
- server/src/main/java/com/codueon/boostUp/domain/vo/AuthVO.java
별도의 요청 없이 액세스 토큰이 만료됐을 때 로그아웃 시 에러가 나던 부분 수정
> fix: 로그아웃 버그 수정

- server/src/main/java/com/codueon/boostUp/global/security/config/SecurityConfig.java
fix : SecurityFilterChain 수정 1
> fix : SecurityFilterChain 수정 1

- client/next.config.js
- client/pages/_app.tsx
- client/pages/index.tsx
- client/pages/lesson/[id].tsx
- 이미지 최적화 도메인 설정 및 metadata 위치 변경
> Refactor/things#567 이미지 최적화 도메인 설정 및 metadata 위치 변경

- client/components/Header/Header.tsx
- client/components/Maincard/Card.tsx
- client/components/detailComp/DetailExtra.tsx
- client/pages/_app.tsx
#567 
refacor: 불필요 코드 라인 삭제 및 SEO image alt 속성 추가
> refacor: 불필요 코드 라인 삭제 및 SEO image alt 속성 추가

- client/atoms/mypage/myPageAtom.tsx
- client/pages/api/auth/[...nextauth].ts
- client/pages/login.tsx
카카오 소셜로그인 버튼 삭제(보류)
구글 소셜 로그인 구현 (테스트 필요)
> featGoogleOauth

- client/components/Header/Header.tsx
- client/hooks/auth/usePostLogin.tsx
- login시 lessonExistence 값 localstorage에 저장
- lessonExistence값을 통해 과외등록 가능여부 판단
> feat: lessonExistence값 반영

- client/components/Header/Header.tsx
- client/hooks/auth/usePostLogin.tsx
- login시 lessonExistence 값 localstorage에 저장
- lessonExistence값을 통해 과외등록 가능여부 판단
> feat: lessonExistence값 반영 (#670)

- server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
> fix: websocketUtils 수정

- server/src/main/java/com/codueon/boostUp/domain/bookmark/dto/GetBookmark.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/entity/Bookmark.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepository.java
- server/src/main/java/com/codueon/boostUp/domain/bookmark/repository/BookmarkRepositoryImpl.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/Curriculum.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonAddress.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/LessonInfo.java
- server/src/main/java/com/codueon/boostUp/domain/lesson/entity/ProfileImage.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/entity/Review.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepository.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/repository/ReviewRepositoryImpl.java
- 글 등록 시 진행방식 1000자, 재직회사/학력 500자 설정
> refactor: Lesson 등록 시 글자 수 제한

- server/src/main/java/com/codueon/boostUp/domain/chat/controller/ChatRoomController.java
- server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/MakeChatRoomEventListener.java
- server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendMessageEventListener.java
- server/src/main/java/com/codueon/boostUp/domain/chat/event/listener/SendNewChatAlarmEventListener.java
- server/src/main/java/com/codueon/boostUp/domain/chat/repository/redis/RedisChatRoom.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatAlarmService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/ChatRoomService.java
- server/src/main/java/com/codueon/boostUp/domain/chat/service/EventMessageService.java
- server/src/main/java/com/codueon/boostUp/domain/reveiw/service/ReviewEventService.java
- server/src/test/java/com/codueon/boostUp/domain/chat/ChatRoomTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/message/controller/SendChatTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/message/event/SendMessageEventListenerTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/room/controller/CreateChatRoomTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/room/event/MakeChatRoomEventListenerTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/utils/ChatMethodUtils.java
- server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
- server/src/test/java/com/codueon/boostUp/domain/utils/DataForTest.java
makeChatRoomEventListener 테스트 코드 작성
> test: makeChatRoomEventListener 테스트 코드 작성

- client/components/Detail/ApplyModal.tsx
- client/components/Detail/DetailButtons.tsx
- client/components/Header/Header.tsx
- client/components/Maincard/Card.tsx
- client/components/Mypage/AcceptModal.tsx
- client/components/Mypage/ApplicationList.tsx
- client/components/Mypage/DeclineModal.tsx
- client/components/Mypage/ReviewModal.tsx
- client/components/Navbar/Navbar.tsx
- client/components/createModal/Curriculum.tsx
- client/components/createModal/ExtraInfo.tsx
- client/components/detailComp/DetailCurModi.tsx
- client/components/detailComp/DetailExtraModi.tsx
#567 
- 글작성 & 수정 모달 : 재직회사 500글자, 진행방식 1000글자
- alert 창 통일
- swal은 확인이 한 번 더 필요한 것에 적용(로그인 필요 기능, 삭제, 취소 등등)
- 그 외는 toastify 적용
> [FE] 리팩터링 - 최대 글자 수 제한 및 alert 창 통일 

- client/apis/auth/getGoogleLogin.tsx
- client/components/Mypage/MypageInfo.tsx
- client/hooks/main/useGetMainCard.tsx
- client/pages/login.tsx
> feat 회원탈퇴삭제

- server/build.gradle
- server/src/main/java/com/codueon/boostUp/BoostUpApplication.java
- server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatMessage.java
- server/src/main/java/com/codueon/boostUp/domain/chat/entity/ChatRoom.java
- server/src/main/java/com/codueon/boostUp/domain/chat/repository/querydsl/ChatRoomRepository.java
- server/src/main/java/com/codueon/boostUp/global/batch/config/BatchConfig.java
- server/src/test/java/com/codueon/boostUp/BoostUpApplicationTests.java
- server/src/test/java/com/codueon/boostUp/config/JpaQueryFactoryConfig.java
- server/src/test/java/com/codueon/boostUp/domain/chat/WebSocketAuthServiceTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/message/repository/ChatRepositoryTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/room/repository/ChatRoomRepositoryTest.java
- server/src/test/java/com/codueon/boostUp/domain/chat/utils/DataForChat.java
- server/src/test/java/com/codueon/boostUp/domain/chat/utils/WebSocketTestUtils.java
- chatRepository와 chatRoomRepository 테스트를 완료했습니다.
- EnableBatchProcessing 애너테이션을 메인 Application에 등록 시 DataForTest 사용 시 데이터가 정상적으로 저장되지 않는 문제가 발생했었습니다. 따라서 해당 애너테이션을 별도의 Configuration 클래스를 만들어 클래스를 등록하도록 변경했습니다.
<br>
해당 이슈의 문제점은 링크에서 확인할 수 있습니다.
<b><a href="https://github.com/spring-projects/spring-boot/issues/10703">링크 참조</a></b>
> test: chat/chatRoomRepository 테스트 완료

- client/README.md
> docs: client 폴더 리드미 업데이트

- client/components/Maincard/Card.tsx
- client/components/Maincard/Cards.tsx
- client/hooks/auth/useDeleteLogout.tsx
- client/hooks/main/usePostWrite.tsx
- client/pages/index.tsx
- 메인페이지 SSR data fetching 방식으로 전환
- 카드정보 api요청 enabled : false로 수정 및 관련 invalidequeries 수동으로 전환
> refactor: Transfer to SSRDataFetch

- client/README.md
- client/components/Maincard/Card.tsx
- client/components/Maincard/Cards.tsx
- client/hooks/auth/useDeleteLogout.tsx
- client/hooks/main/usePostWrite.tsx
- client/pages/index.tsx
refactor: Transfer to SSRDataFetch 작업 건 main 브랜치로 병합요청
> refactor: Transfer to SSRDataFetch 작업 건 main 브랜치로 병합요청

- client/components/Maincard/Card.tsx
- client/pages/index.tsx
- fetchData함수에서 getServerSideProps로 변경
> refactor:transfer to SSRDataFetch
